# Generated by Django 4.2 on 2025-08-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(default='🔗', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='url',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='url',
            name='unique_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(default=shortener.models.generate_short_code, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires', models.DateTimeField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('api_calls_limit', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_unique', models.BooleanField(default=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shortener.url')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddField(
            model_name='url',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.urlcategory'),
        ),
        migrations.AddField(
            model_name='url',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.domain'),
        ),
    ]
