from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('advanced_shorten', views.advanced_shorten, name='api_shorten'),
  
    path('url_analytics/<str:short_code>', views.url_analytics, name='url_analytics'),
    path('', views.Comming_Soon_Page, name='coming_soon'),
    path('advanced_shorten', views.advanced_shorten, name='advanced_shorten'),
    path('api/shorten/', views.api_shorten, name='api_shorten'),
    path('stats/<str:short_code>/', views.url_stats, name='url_stats'),
    path('<str:short_code>/', views.redirect_url, name='redirect_url'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'), 
    path('shorten_url', views.shorten_url, name='shorten_url'),
    # path('register/', views.register, name='register'),
    # path('profile/', views.profile, name='profile'),
    # path('delete/<str:short_code>/', views.delete_url, name='delete_url'),
    # path('edit/<str:short_code>/', views.edit_url, name='edit_url'),
    # path('custom_shorten/', views.custom_shorten, name='custom_shorten'),
    # path('api/custom_shorten/', views.api_custom_shorten, name='api_custom_shorten'),
    # path('api/token/', views.api_token, name='api_token'),
    # path('api/token/refresh/', views.api_token_refresh, name='api_token_refresh'),
    # path('api/protected/', views.api_protected, name='api_protected'),
    # path('api/user_urls/', views.api_user_urls, name='api_user_urls'),
    # path('api/delete_url/<str:short_code>/', views.api_delete_url, name='api_delete_url'),
    # path('api/edit_url/<str:short_code>/', views.api_edit_url, name='api_edit_url'),
    # path('api/url_stats/<str:short_code>/', views.api_url_stats, name='api_url_stats'),
    # path('api/all_urls/', views.api_all_urls, name='api_all_urls'),
    # path('api/create_user/', views.api_create_user, name='api_create_user'),
    # path('api/login_user/', views.api_login_user, name='api_login_user'),
    # path('api/logout_user/', views.api_logout_user, name='api_logout_user'),
    # path('api/user_profile/', views.api_user_profile, name='api_user_profile'),
    # path('api/edit_profile/', views.api_edit_profile, name='api_edit_profile'),
    # path('api/change_password/', views.api_change_password, name='api_change_password'),
    # path('api/reset_password/', views.api_reset_password, name='api_reset_password'),
    # path('api/reset_password_confirm/', views.api_reset_password_confirm, name='api_reset_password_confirm'),
    # path('api/dashboard_stats/', views.api_dashboard_stats, name='api_dashboard_stats'),
    # path('api/recent_urls/', views.api_recent_urls, name='api_recent_urls'),
    # path('api/popular_urls/', views.api_popular_urls, name='api_popular_urls'),
    # path('api/url_analytics/<str:short_code>/', views.api_url_analytics, name='api_url_analytics'),
    # path('api/user_analytics/', views.api_user_analytics, name='api_user_analytics'),
    # path('api/system_analytics/', views.api_system_analytics, name='api_system_analytics'),
    # path('api/advanced_shorten/', views.api_advanced_shorten, name='api_advanced_shorten'),
    # path('api/custom_shorten/', views.api_custom_shorten, name='api_custom_shorten'),
    # path('api/documentation/', views.api_documentation, name='api_documentation'),
    # path('api/help/', views.api_help, name='api_help'),
    # path('api/support/', views.api_support, name='api_support'),
    # path('api/feedback/', views.api_feedback, name='api_feedback'),
    # path('api/terms/', views.api_terms, name='api_terms'),
    # path('api/privacy/', views.api_privacy, name='api_privacy'),
    # path('api/about/', views.api_about, name='api_about'),
    # path('api/contact/', views.api_contact, name='api_contact'),
    # path('api/faq/', views.api_faq, name='api_faq'),
    # path('api/status/', views.api_status, name='api_status'),
    # path('api/metrics/', views.api_metrics, name='api_metrics'),
    # path('api/health/', views.api_health, name='api_health'),
    # path('api/version/', views.api_version, name='api_version'),
    # path('api/whoami/', views.api_whoami, name='api_whoami'),
    # path('api/csrf/', views.api_csrf, name='api_csrf'),
    # path('api/docs/', views.api_docs, name='api_docs'),
    # path('api/schema/', views.api_schema, name='api_schema'),
    # path('api/redoc/', views.api_redoc, name='api_redoc'),
    # path('api/swagger/', views.api_swagger, name='api_swagger'),
    # path('api/openapi/', views.api_openapi, name='api_openapi'),
    # path('api/graphql/', views.api_graphql, name='api_graphql'),
    # path('api/graphiql/', views.api_graphiql, name='api_graphiql'),
    # path('api/playground/', views.api_playground, name='api_playground'),
    # path('api/altair/', views.api_altair, name='api_altair'),
    # path('api/insomnia/', views.api_insomnia, name='api_insomnia'),
    # path('api/postman/', views.api_postman, name='api_postman'),
    # path('api/rest/', views.api_rest, name='api_rest'),
    # path('api/rest_framework/', views.api_rest_framework, name='api_rest_framework'),
    # path('api/django/', views.api_django, name='api_django'),
    # path('api/django_rest_framework/', views.api_django_rest_framework, name='api_django_rest_framework'),

    # path('api/drf_yasg/', views.api_drf_yasg, name='api_drf_yasg'),
    # path('api/drf_spectacular/', views.api_drf_spectacular, name='api_drf_spectacular'),
    # path('api/rest_framework_swagger/', views.api_rest_framework_swagger, name='api_rest_framework_swagger'),
    # path('api/rest_framework_docs/', views.api_rest_framework_docs, name='api_rest_framework_docs'),
    # path('api/rest_framework_json_api/', views.api_rest_framework_json_api, name='api_rest_framework_json_api'),
    # path('api/rest_framework_xml/', views.api_rest_framework_xml, name='api_rest_framework_xml'),
    # path('api/rest_framework_yaml/', views.api_rest_framework_yaml, name='api_rest_framework_yaml'),
    # path('api/rest_framework_csv/', views.api_rest_framework_csv, name='api_rest_framework_csv'),
    # path('api/rest_framework_excel/', views.api_rest_framework_excel, name='api_rest_framework_excel'),
    # path('api/rest_framework_pdf/', views.api_rest_framework_pdf, name='api_rest_framework_pdf'),
    # path('api/rest_framework_html/', views.api_rest_framework_html, name='api_rest_framework_html'),
    # path('api/rest_framework_browsable_api/', views.api_rest_framework_browsable_api, name='api_rest_framework_browsable_api'),
    
    # path('api/rest_framework_auth/', views.api_rest_framework_auth, name='api_rest_framework_auth'),
    # path('api/rest_framework_permissions/', views.api_rest_framework_permissions, name='api_rest_framework_permissions'),
    
    # path('api/rest_framework_throttling/', views.api_rest_framework_throttling, name='api_rest_framework_throttling'),
    
    # path('api/rest_framework_pagination/', views.api_rest_framework_pagination, name='api_rest_framework_pagination'),
    # path('api/rest_framework_filters/', views.api_rest_framework_filters, name='api_rest_framework_filters'),
    # path('api/rest_framework_search/', views.api_rest_framework_search, name='api_rest_framework_search'),
    # path('api/rest_framework_ordering/', views.api_rest_framework_ordering, name='api_rest_framework_ordering'),
    # path('api/rest_framework_versioning/', views.api_rest_framework_versioning, name='api_rest_framework_versioning'),
    # path('api/rest_framework_caching/', views.api_rest_framework_caching, name='api_rest_framework_caching'),
    # path('api/rest_framework_schemas/', views.api_rest_framework_schemas, name='api_rest_framework_schemas'),
    # path('api/rest_framework_swagger_ui/', views.api_rest_framework_swagger_ui, name='api_rest_framework_swagger_ui'),
    # path('api/rest_framework_redoc/', views.api_rest_framework_redoc, name='api_rest_framework_redoc'),
    # path('api/rest_framework_graphql/', views.api_rest_framework_graphql, name='api_rest_framework_graphql'),
    # path('api/rest_framework_graphiql/', views.api_rest_framework_graphiql, name='api_rest_framework_graphiql'),
    


    # path('api/rest_framework_playground/', views.api_rest_framework_playground, name='api_rest_framework_playground'),



    ]

